[options]
CacheDir = /tmp/cache/pacman/
ParallelDownloads = 5
Architecture = auto
CheckSpace
Color

# Repositories

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
