[project]
name        = "dotfiles"
description = "Sensible system dotfiles"
classifiers = ["Private :: Do Not Upload"]
version     = "1.0"
license     = "MIT"
dependencies = [
    "attrs",
    "cyclopts",
    "pydantic",
]

[project.scripts]
dot     = "dotfiles.__main__:main"
get-yay = "dotfiles.pacman:Yay.get"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
